-- AlterTable
ALTER TABLE "Style" ALTER COLUMN "xl" DROP NOT NULL,
ALTER COLUMN "lg" DROP NOT NULL,
ALTER COLUMN "md" DROP NOT NULL,
ALTER COLUMN "sm" DROP NOT NULL;

-- AlterTable
ALTER TABLE "User" ADD COLUMN     "phone" TEXT;
