import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "../globals.css";
import Header from "./_Components/layout/Header";
import Sidebar from "./_Components/layout/Sidebar";
import { ThemeProvider } from "@/Context/ThemeContext";
import { Provider } from "@/Context/EditorContext";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased p-4 pb-0 theme-gradient min-h-screen`}
      >
        <ThemeProvider>
          <Provider>

            <Header brand="kama" />
            <div className="flex flex-1 h-[85.65vh]">
              <Sidebar />
              <div className="flex-1 h-full">{children}</div>
            </div>
          </Provider>
        </ThemeProvider>
      </body>
    </html>
  );
}
